### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by kmoughon** [miyukki/node-atem#1]
seems the methods used in the examples are not defined,  are these just placeholders for code still in development? I would be very interested if you have any updates.

**Comment by miyukki** [comment]
@kmoughon 
Sorry :disappointed:  This library is development..

Some method name in example was changed. example is below:
`setProgramInput` -> `changeProgramInput`
`changeTransitionAuto` -> `autoTransition`
Some defined method was working my ATEM Switcher.

And, not defined `#on('change')` method for watching parameter values.

Please wait for any updates.

**Comment by kmoughon** [comment]
Thanks for the quick reply. I only interested in reading the preview and program outputs, and ideally having a event to catch that. If you have any updates to help with that i would be interested, but i understand it is in development, and appreciate your work!

**Comment by Dev1an** [comment]
@kmoughon Did you check this module: https://www.npmjs.com/package/atem
You can easily catch `program` and `preview` events with it and it's production ready.

``` javascript
var Atem = require('atem') // Load the atem module
var myAtemDevice = new Atem("10.1.0.9")

myAtemDevice.on('previewBus', function(source) {
  // Source is a number representing the source that is in preview
  // You can get more info about the source number with the following function
  var info  = Atem.getSourceInfo(source)
})

myAtemDevice.on('programBus', function(source) {
  // Source is a number representing the source that is in program
})
```

**Comment by miyukki** [comment]
This module was transferred. See: https://github.com/applest/node-applest-atem
