### ISSUE TITLE
Control AUXes

### ISSUE THREAD

**Issue by OB3RG** [miyukki/node-atem#2]
This is more a request then an issue. 

Would be super if there was a function where you could control Auxes on the atem. Like setAux(auxNr, inputNr). 

Would gladly assist with this, but the controlling the ATEM this way is new to me. Still figuring things out.

**Comment by miyukki** [comment]
@OB3RG  Hi, thanks for opinion.

I don't have a ATEM Switcher supporting aux. This library based on own packet analysis and below project.
https://github.com/kasperskaarhoj/Arduino-Library-for-ATEM-Switchers/blob/master/ATEM.cpp

When I can afford, it will support command of aux functions. 
Have been waiting for update.
